### ISSUE TITLE
общая команда для всех имен

### ISSUE THREAD

**Issue by cmlimm** [cmlimm/bmetr#2]
сейчас команда отдельная для каждого имени, некрасиво, но работает, хочется красиво, чтобы была !brs_имярек и бот сам передавал функции имя

**Comment by kirillzx** [comment]
там можно сделать так что когда ты пишешь он чекает кто это пишет и можно передавать юзера тогда сразу

**Comment by cmlimm** [comment]
ну смотри я же могу захотеть чекнуть брс сани например так что так наверное перебор

**Comment by kirillzx** [comment]
Да понял, ок подумаю
